CREATE TABLE BRANDS (
	BRAND_ID NUMBER NOT NULL,
    BRAND_NAME VARCHAR(30)
);

CREATE TABLE PRODUCTS (
	PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR(30),
    PRODUCT_DESCRIPTION VARCHAR(50)
);

CREATE TABLE PRICES (
	BRAND_ID NUMBER NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	PRICE_LIST NUMBER(10,2),
	PRODUCT_ID NUMBER NOT NULL,
	PRIORITY NUMBER(10),
	PRICE NUMBER(10,2),
	CURR VARCHAR(3)
);

ALTER TABLE BRANDS
ADD PRIMARY KEY (BRAND_ID);

ALTER TABLE PRODUCTS
ADD PRIMARY KEY (PRODUCT_ID);

ALTER TABLE PRICES
ADD PRIMARY KEY (BRAND_ID,PRODUCT_ID,START_DATE,END_DATE);

ALTER TABLE PRICES
    ADD FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS (PRODUCT_ID);

ALTER TABLE PRICES
    ADD FOREIGN KEY (BRAND_ID)
    REFERENCES BRANDS(BRAND_ID);